version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 299
      runas: ubuntu